spring.application.name=OrganizaCasa

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/organizacasa
spring.datasource.username=postgres
spring.datasource.password=Filhos02

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs